<link rel="alternate" type="application/rss+xml" href="<?php echo $this->baseUrl(). "/feed/rss/id/".$this->materi->id_materi;?>"/>
<section id="one">
        <h2><?php echo $this->materi->judul?></h2>
        <p>
            <span class="fa fa-table"></span>&nbsp;<?php echo $this->materi->tanggal.' '.$this->materi->bulan.' '.$this->materi->tahun;?> / 
            <span class="fa fa-book"></span>&nbsp;<?php echo $this->materi->mapel?>&nbsp;&nbsp;&nbsp;&nbsp;
            <?php if($this->input != "tidak" && $this->materi->user == $this->input) : ?>
            <span class="fa fa-edit"></span>&nbsp;<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editmateri', 'id' => $this->materi->id_materi))?>">Edit Materi</a>
            <?php endif;?>
        </p>
        <hr/>
        <p><?php $cari = array("<?","?>");
                 $ganti = array("&lt;?","?&gt;");
                 $mat = $this->materi->materi;
                 $mat = str_replace($cari, $ganti, $mat);
                 echo $mat;?></p>
        <hr/>
        <div class="row">
            <img style="float: left" src="<?php echo $this->baseUrl()."/img/share/SpradTheWord.png"?>">
            <div style="float: left; width: 100%">
                <img style="float: left; margin-right: 10px" src="<?php echo $this->baseUrl()."/img/share/Arrow.png"?>">
                <div style="width: 70%; float: left">
                    <span onclick="open1()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/1.png"?>">
                    </span>
                    <span onclick="open2()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/2.png"?>">
                    </span>
                    <span onclick="open3()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/3.png"?>">
                    </span>
                    <span onclick="open4()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/4.png"?>">
                    </span>
                    <span onclick="open5()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/5.png"?>">
                    </span>
                    <span onclick="open6()" style="box-shadow: 0px 0px 3px #000; float: left; width: 30px; height: 30px; margin-right: 10px; margin-top: 5px">
                        <img style="width: 30px" src="<?php echo $this->baseUrl()."/img/share/6.png"?>">
                    </span>
                </div>
            </div>
            
        </div>
        <script>
            function open1() {
                var myWindow = window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
            
            function open2() {
                var myWindow = window.open('https://twitter.com/intent/tweet?text=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
            
            function open3() {
                var myWindow = window.open('https://plus.google.com/share?url=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
            
            function open4() {
                var myWindow = window.open('https://mail.google.com/mail/u/0/?view=cm&fs=1&to&su&ui=2&tf=1&body=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
            
            function open5() {
                var myWindow = window.open('https://www.linkedin.com/cws/share?url=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
            
            function open6() {
                var myWindow = window.open('http://www.tumblr.com/share/link?url=<?php echo $this->serverUrl() . $this->url(array("controller" => "index", "action" => "materi", "id" => $this->materi->id_materi))?>', '', 'width=500, height=600');
                return false;
            }
        </script>
</section>