<section>
    <div class="row">
        <div class="4u 12u$(small)">
            <label>Kelas</label>
            <select class="kelas">
                <option value="">-Pilih-</option>
                <?php foreach($this->kelas as $kelas):?>
                <option value="<?php echo $kelas["nama"];?>"><?php echo $kelas["nama"];?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="4u 12u$(small)">
            <label>Mata Pelajaran</label>
            <select class="mapel">
                <option value="">-Pilih-</option>
                <?php foreach($this->mapel as $mapel):?>
                <option value="<?php echo $mapel["mapel"];?>"><?php echo $mapel["mapel"];?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="4u$ 12u$(small)">
            <label>Judul</label>
            <div class="row uniform 30%">
                <div class="8u 12u$(small)">
                    <input placeholder="Judul" type="text" class="key"/>
                </div>
                <div class="4u$ 12u$(small)">
                    <a class="cari"><div style="padding: 0.75em; height:2.75em;border-radius: 0.35em;border: 3px solid #EFEFEF;color: #787878;cursor: pointer;display: inline-block;line-height: 1em;">Cari</div></a>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <h4>Hasil :</h4>
    <hr/>
    <?php if (is_array($this->hasil) && count($this->hasil) != 0): ?>
        <?php $i=1; foreach ($this->hasil as $hasil):?>
        <h4><?php echo $i . ". "?>
            <a href="<?php echo $this->url(array('controller'=>'index','action'=>'materi','id'=>$hasil["id_materi"]))?>"><?php echo $hasil["judul"]?></a>
        </h4>
        <br/>
        <?php $i++; endforeach;?>
    <?php else : ?>
    <center>Hasil Kosong</center>
    <?php endif; ?>
</section>
<script>             
$(".cari").click(function(){
   kelas = $(".kelas").val();
   mapel = $(".mapel").val();
   judul = $(".key").val();
   cari = "/index/cari/?kata="+judul+";"+kelas+";"+mapel
   window.open(cari, '_self');
}); 
</script>